import type {
  ArtifactRecord,
  GenerationProviderManifest,
  KeyboardProject,
  ProductFamilyManifest,
  ProjectJobRecord,
  ProjectRecords,
  ValidationReport,
  WorkspaceStageManifest,
} from "../types/project";

const CREATED_AT = "2026-05-01T14:30:00.000Z";
const UPDATED_AT = "2026-05-01T18:05:00.000Z";

const DEMO_STAGES: WorkspaceStageManifest[] = [
  {
    id: "define",
    label: "Define",
    description: "Choose family, modules, and hardware baseline.",
    requires_project: false,
    modules: ["switch_explorer"],
    preview_mode: "3d",
  },
  {
    id: "layout",
    label: "Layout",
    description: "Arrange controls and tune spacing in 2D and 3D.",
    requires_project: true,
    modules: ["layout_editor"],
    preview_mode: "3d",
  },
  {
    id: "appearance",
    label: "Appearance",
    description: "Review accepted visible assets and finish direction.",
    requires_project: true,
    modules: ["keycap_styler"],
    preview_mode: "3d",
  },
  {
    id: "electronics",
    label: "Electronics",
    description: "Matrix strategy, GPIO allocation, and firmware target.",
    requires_project: true,
    modules: ["pcb_panel"],
    preview_mode: "3d",
  },
  {
    id: "validate",
    label: "Validate",
    description: "Run family-aware checks before export.",
    requires_project: true,
    modules: ["export_panel"],
    preview_mode: "3d",
  },
  {
    id: "export",
    label: "Export",
    description: "Ship traceable artifacts instead of loose files.",
    requires_project: true,
    modules: ["export_panel"],
    preview_mode: "3d",
  },
];

const baseProject: KeyboardProject = {
  project_id: "public_demo_streamdeck",
  spec_version: 2,
  product_domain: "control_surface",
  product_family: "streamdeck",
  name: "Creator Deck Launch Demo",
  revision: 7,
  status: "validated",
  created_at: CREATED_AT,
  updated_at: UPDATED_AT,
  template: "streamdeck_display_3x5",
  layout: {
    unit_pitch_mm: 19.05,
    keys: [],
    elements: [
      { id: "display", element_type: "display", label: "Status", footprint_id: "oled_128x32", x_mm: 12, y_mm: 8, w_mm: 71, h_mm: 22, rotation_deg: 0, mounting: {}, appearance_ref: null, electrical_ref: "scene_status", metadata: {}, stabilizer: "none", keycap_asset_id: null, row: null, col: null },
      { id: "enc_master", element_type: "encoder", label: "Mix", footprint_id: "ec11_encoder", x_mm: 94, y_mm: 6, w_mm: 24, h_mm: 24, rotation_deg: 0, mounting: {}, appearance_ref: "asset_graphite_knob", electrical_ref: "master_volume", metadata: {}, stabilizer: "none", keycap_asset_id: "asset_graphite_knob", row: null, col: null },
      { id: "btn_1", element_type: "button", label: "Cam", footprint_id: "mx_switch", x_mm: 12, y_mm: 42, w_mm: 19.05, h_mm: 19.05, rotation_deg: 0, mounting: {}, appearance_ref: "asset_graphite_cap", electrical_ref: "scene_cam", metadata: {}, stabilizer: "none", keycap_asset_id: "asset_graphite_cap", row: 0, col: 0 },
      { id: "btn_2", element_type: "button", label: "Cut", footprint_id: "mx_switch", x_mm: 34, y_mm: 42, w_mm: 19.05, h_mm: 19.05, rotation_deg: 0, mounting: {}, appearance_ref: "asset_graphite_cap", electrical_ref: "scene_cut", metadata: {}, stabilizer: "none", keycap_asset_id: "asset_graphite_cap", row: 0, col: 1 },
      { id: "btn_3", element_type: "button", label: "B", footprint_id: "mx_switch", x_mm: 56, y_mm: 42, w_mm: 19.05, h_mm: 19.05, rotation_deg: 0, mounting: {}, appearance_ref: "asset_graphite_cap", electrical_ref: "scene_b", metadata: {}, stabilizer: "none", keycap_asset_id: "asset_graphite_cap", row: 0, col: 2 },
      { id: "btn_4", element_type: "button", label: "Audio", footprint_id: "mx_switch", x_mm: 78, y_mm: 42, w_mm: 19.05, h_mm: 19.05, rotation_deg: 0, mounting: {}, appearance_ref: "asset_graphite_cap", electrical_ref: "audio_mute", metadata: {}, stabilizer: "none", keycap_asset_id: "asset_graphite_cap", row: 0, col: 3 },
      { id: "btn_5", element_type: "button", label: "FX", footprint_id: "mx_switch", x_mm: 100, y_mm: 42, w_mm: 19.05, h_mm: 19.05, rotation_deg: 0, mounting: {}, appearance_ref: "asset_graphite_cap", electrical_ref: "effects_toggle", metadata: {}, stabilizer: "none", keycap_asset_id: "asset_graphite_cap", row: 0, col: 4 },
      { id: "btn_6", element_type: "button", label: "Rec", footprint_id: "mx_switch", x_mm: 12, y_mm: 64, w_mm: 19.05, h_mm: 19.05, rotation_deg: 0, mounting: {}, appearance_ref: "asset_graphite_cap", electrical_ref: "record_arm", metadata: {}, stabilizer: "none", keycap_asset_id: "asset_graphite_cap", row: 1, col: 0 },
      { id: "btn_7", element_type: "button", label: "Go", footprint_id: "mx_switch", x_mm: 34, y_mm: 64, w_mm: 19.05, h_mm: 19.05, rotation_deg: 0, mounting: {}, appearance_ref: "asset_graphite_cap", electrical_ref: "macro_go", metadata: {}, stabilizer: "none", keycap_asset_id: "asset_graphite_cap", row: 1, col: 1 },
      { id: "btn_8", element_type: "button", label: "Clip", footprint_id: "mx_switch", x_mm: 56, y_mm: 64, w_mm: 19.05, h_mm: 19.05, rotation_deg: 0, mounting: {}, appearance_ref: "asset_graphite_cap", electrical_ref: "clip_mark", metadata: {}, stabilizer: "none", keycap_asset_id: "asset_graphite_cap", row: 1, col: 2 },
      { id: "btn_9", element_type: "button", label: "Chat", footprint_id: "mx_switch", x_mm: 78, y_mm: 64, w_mm: 19.05, h_mm: 19.05, rotation_deg: 0, mounting: {}, appearance_ref: "asset_graphite_cap", electrical_ref: "chat_scene", metadata: {}, stabilizer: "none", keycap_asset_id: "asset_graphite_cap", row: 1, col: 3 },
      { id: "btn_10", element_type: "button", label: "Cue", footprint_id: "mx_switch", x_mm: 100, y_mm: 64, w_mm: 19.05, h_mm: 19.05, rotation_deg: 0, mounting: {}, appearance_ref: "asset_graphite_cap", electrical_ref: "cue_scene", metadata: {}, stabilizer: "none", keycap_asset_id: "asset_graphite_cap", row: 1, col: 4 },
      { id: "btn_11", element_type: "button", label: "Live", footprint_id: "mx_switch", x_mm: 12, y_mm: 86, w_mm: 19.05, h_mm: 19.05, rotation_deg: 0, mounting: {}, appearance_ref: "asset_graphite_cap", electrical_ref: "stream_live", metadata: {}, stabilizer: "none", keycap_asset_id: "asset_graphite_cap", row: 2, col: 0 },
      { id: "btn_12", element_type: "button", label: "Wide", footprint_id: "mx_switch", x_mm: 34, y_mm: 86, w_mm: 19.05, h_mm: 19.05, rotation_deg: 0, mounting: {}, appearance_ref: "asset_graphite_cap", electrical_ref: "wide_scene", metadata: {}, stabilizer: "none", keycap_asset_id: "asset_graphite_cap", row: 2, col: 1 },
      { id: "btn_13", element_type: "button", label: "Tight", footprint_id: "mx_switch", x_mm: 56, y_mm: 86, w_mm: 19.05, h_mm: 19.05, rotation_deg: 0, mounting: {}, appearance_ref: "asset_graphite_cap", electrical_ref: "tight_scene", metadata: {}, stabilizer: "none", keycap_asset_id: "asset_graphite_cap", row: 2, col: 2 },
      { id: "btn_14", element_type: "button", label: "Outro", footprint_id: "mx_switch", x_mm: 78, y_mm: 86, w_mm: 19.05, h_mm: 19.05, rotation_deg: 0, mounting: {}, appearance_ref: "asset_graphite_cap", electrical_ref: "outro_macro", metadata: {}, stabilizer: "none", keycap_asset_id: "asset_graphite_cap", row: 2, col: 3 },
      { id: "btn_15", element_type: "button", label: "Safe", footprint_id: "mx_switch", x_mm: 100, y_mm: 86, w_mm: 19.05, h_mm: 19.05, rotation_deg: 0, mounting: {}, appearance_ref: "asset_graphite_cap", electrical_ref: "panic_cut", metadata: {}, stabilizer: "none", keycap_asset_id: "asset_graphite_cap", row: 2, col: 4 },
    ],
  },
  switch_profile: {
    family: "mx",
    part_id: "gateron_mx_brown",
  },
  style_request: {
    provider: "meshy",
    prompt: "brushed graphite broadcast deck with subtle indigo legends",
    preset: "industrial",
    variant_count: 4,
  },
  keycap_assets: [
    {
      asset_id: "asset_graphite_cap",
      source: "generated",
      provider: "meshy",
      prompt: "graphite broadcast keycap",
      mesh_path: null,
      preview_mesh_path: null,
      unit_sizes: [1],
      normalized: true,
      watertight: true,
      acceptance_state: "accepted",
    },
    {
      asset_id: "asset_graphite_knob",
      source: "generated",
      provider: "meshy",
      prompt: "machined graphite encoder knob",
      mesh_path: null,
      preview_mesh_path: null,
      unit_sizes: [1],
      normalized: true,
      watertight: true,
      acceptance_state: "production_ready",
    },
    {
      asset_id: "asset_alt_cap",
      source: "generated",
      provider: "meshy",
      prompt: "matte ceramic accent cap",
      mesh_path: null,
      preview_mesh_path: null,
      unit_sizes: [1],
      normalized: true,
      watertight: true,
      acceptance_state: "candidate",
    },
  ],
  pcb: {
    controller: "rp2040",
    matrix_mode: "hybrid_control_surface",
    diode_direction: "COL2ROW",
    matrix_rows: 4,
    matrix_cols: 4,
    board_outline_source: "layout",
    drc_passed: true,
    gerber_path: null,
    kicad_project_path: null,
  },
  exports: {
    bundle_id: "bundle_demo_launch",
    bundle_path: null,
    exported_at: UPDATED_AT,
    validation_report_id: "vr_demo_launch",
  },
  metadata: {
    demo_mode: true,
    launch_surface: "github_pages",
  },
  derived: {
    electronics: {
      matrix_rows: 4,
      matrix_cols: 4,
      matrix_strategy: "balanced_control_surface",
      matrix_controls: 15,
      direct_controls: 2,
      matrix_pins: 8,
      direct_pins: 2,
      pins_needed: 10,
      gpio_budget: 26,
      gpio_remaining: 16,
      firmware_target: "hid_control_surface",
      control_protocol: "usb_hid_macro",
      direct_pin_usage: [
        { element_type: "display", control_count: 1, pins_per_control: 1, total_pins: 1 },
        { element_type: "encoder", control_count: 1, pins_per_control: 1, total_pins: 1 },
      ],
    },
    mechanical: {
      summary: {
        project_id: "public_demo_streamdeck",
        revision: 7,
        status: "compiled",
        mechanical_kind: "panel",
        geometry_kind: "hybrid_control_panel",
        key_count: 15,
        element_count: 17,
        cutout_summary: {
          button: 15,
          display: 1,
          encoder: 1,
        },
        mounting_hole_count: 4,
        plate_width_mm: 118.05,
        plate_height_mm: 104.05,
        artifact_urls: {
          panel_dxf: "#",
        },
        artifact_ids: ["mech_panel_dxf_r7", "mech_panel_summary_r7"],
        compiled_at: UPDATED_AT,
      },
      artifact_ids: ["mech_panel_dxf_r7", "mech_panel_summary_r7"],
      mechanical_kind: "panel",
      source_revision: 7,
      source_spec_hash: "demo_spec_hash_streamdeck",
      compiled_at: UPDATED_AT,
    },
  },
  assets: {},
  jobs: {},
};

const baseValidationReport: ValidationReport = {
  report_id: "vr_demo_launch",
  project_id: "public_demo_streamdeck",
  revision: 7,
  status: "warn",
  created_at: UPDATED_AT,
  checks: [
    {
      id: "display_clearance",
      category: "geometry",
      status: "warn",
      details: "Display cutout is valid, but bezel clearance is close to the current shell margin target.",
    },
    {
      id: "gpio_budget",
      category: "electronics",
      status: "pass",
      details: "GPIO allocation fits within the RP2040 budget with 16 pins remaining.",
    },
    {
      id: "asset_acceptance",
      category: "appearance",
      status: "warn",
      details: "One candidate cap variant is still pending review before review-ready export.",
    },
  ],
};

const baseArtifacts: ArtifactRecord[] = [
  {
    artifact_id: "bundle_demo_launch",
    project_id: "public_demo_streamdeck",
    revision: 7,
    kind: "export_bundle",
    artifact_role: "export_bundle",
    domain: "control_surface",
    family: "streamdeck",
    source_revision: 7,
    source_spec_hash: "demo_spec_hash_streamdeck",
    producer_kind: "compiler",
    producer_id: "export_bundler",
    lineage: { project_id: "public_demo_streamdeck", revision: 7, validation_report_id: "vr_demo_launch" },
    acceptance_state: "candidate",
    path: null,
    file_name: "bundle_demo_launch.zip",
    sha256: "demo_bundle_sha",
    content_type: "application/zip",
    details: { artifact_role: "export_bundle", validation_status: "warn" },
    created_at: UPDATED_AT,
  },
  {
    artifact_id: "mech_panel_dxf_r7",
    project_id: "public_demo_streamdeck",
    revision: 7,
    kind: "mechanical_panel_dxf",
    artifact_role: "mechanical_panel_dxf",
    domain: "control_surface",
    family: "streamdeck",
    source_revision: 7,
    source_spec_hash: "demo_spec_hash_streamdeck",
    producer_kind: "compiler",
    producer_id: "mechanical_compiler",
    lineage: { project_id: "public_demo_streamdeck", revision: 7, mechanical_kind: "panel" },
    acceptance_state: "candidate",
    path: null,
    file_name: "panel.dxf",
    sha256: "demo_panel_sha",
    content_type: "application/dxf",
    details: { artifact_role: "mechanical_panel_dxf" },
    created_at: UPDATED_AT,
  },
  {
    artifact_id: "mech_panel_summary_r7",
    project_id: "public_demo_streamdeck",
    revision: 7,
    kind: "mechanical_panel_summary",
    artifact_role: "mechanical_panel_summary",
    domain: "control_surface",
    family: "streamdeck",
    source_revision: 7,
    source_spec_hash: "demo_spec_hash_streamdeck",
    producer_kind: "compiler",
    producer_id: "mechanical_compiler",
    lineage: { project_id: "public_demo_streamdeck", revision: 7, mechanical_kind: "panel" },
    acceptance_state: "candidate",
    path: null,
    file_name: "panel_summary.json",
    sha256: "demo_panel_summary_sha",
    content_type: "application/json",
    details: { artifact_role: "mechanical_panel_summary" },
    created_at: UPDATED_AT,
  },
  {
    artifact_id: "vr_demo_launch",
    project_id: "public_demo_streamdeck",
    revision: 7,
    kind: "validation_report",
    artifact_role: "validation_report",
    domain: "control_surface",
    family: "streamdeck",
    source_revision: 7,
    source_spec_hash: "demo_spec_hash_streamdeck",
    producer_kind: "compiler",
    producer_id: "validation_engine",
    lineage: { project_id: "public_demo_streamdeck", revision: 7, validated: true },
    acceptance_state: "candidate",
    path: null,
    file_name: "validation_report.json",
    sha256: "demo_validation_sha",
    content_type: "application/json",
    details: { artifact_role: "validation_report", status: "warn" },
    created_at: UPDATED_AT,
  },
];

const baseJobs: ProjectJobRecord[] = [
  {
    job_id: "job_demo_meshy",
    project_id: "public_demo_streamdeck",
    revision: 7,
    job_type: "keycap_generation",
    status: "succeeded",
    provider: "meshy",
    external_ref: "meshy_demo_task",
    input_data: { prompt: "machined graphite encoder knob" },
    output_data: { asset_id: "asset_graphite_knob" },
    created_at: CREATED_AT,
    updated_at: UPDATED_AT,
    completed_at: UPDATED_AT,
  },
];

export const publicDemoFamilyManifest: ProductFamilyManifest = {
  domain: "control_surface",
  family: "streamdeck",
  display_name: "Stream Deck",
  description: "Broadcast and creator control surface with one revisioned product record spanning layout, 3D preview, electronics, validation, and export.",
  status: "enabled",
  stages: DEMO_STAGES,
  required_inputs: ["template", "controls", "appearance", "electronics"],
  supported_capabilities: ["layout_editing", "mechanical_compile", "electronics_compile", "export_bundle"],
  available_templates: ["streamdeck_display_3x5"],
  editor_modules: ["layout_editor", "preview_3d"],
  supported_module_types: ["button", "display", "encoder", "usb_port"],
};

export const publicDemoProviders: GenerationProviderManifest[] = [
  {
    id: "meshy",
    display_name: "Meshy",
    description: "Authenticated alpha provider when BREAKGEN_MESHY_API_KEY is configured.",
    status: "disabled",
    feature_flag: null,
    supported_asset_types: ["keycap", "knob", "button_cap"],
    capabilities: ["submit", "poll", "download", "normalize"],
    default_for: ["keycap", "knob"],
  },
  {
    id: "tripo",
    display_name: "Tripo",
    description: "Planned secondary provider behind the same normalized artifact contract.",
    status: "planned",
    feature_flag: "provider_tripo",
    supported_asset_types: ["keycap", "knob", "bezel"],
    capabilities: ["submit", "poll", "download", "normalize"],
    default_for: [],
  },
];

export function createPublicDemoProject(): KeyboardProject {
  return JSON.parse(JSON.stringify(baseProject)) as KeyboardProject;
}

export function createPublicDemoRecords(): ProjectRecords {
  return {
    project_id: "public_demo_streamdeck",
    jobs: JSON.parse(JSON.stringify(baseJobs)) as ProjectJobRecord[],
    artifacts: JSON.parse(JSON.stringify(baseArtifacts)) as ArtifactRecord[],
    latest_validation: JSON.parse(JSON.stringify(baseArtifacts.find((artifact) => artifact.kind === "validation_report") ?? null)) as ArtifactRecord | null,
    latest_validation_report: JSON.parse(JSON.stringify(baseValidationReport)) as ValidationReport,
    latest_export: JSON.parse(JSON.stringify(baseArtifacts.find((artifact) => artifact.kind === "export_bundle") ?? null)) as ArtifactRecord | null,
  };
}
