"""
Export bundle generator.

Creates a ZIP package containing the currently available outputs:
- Plate DXF (laser cutting)
- Firmware metadata (QMK info.json, keymap.json, VIA definition)
- Validation report
- Manifest with artifact hashes and toolchain versions
- Build guide (markdown)

Not yet included (requires additional subsystems):
- Gerber files and drill data (requires KiCad backend worker)
- BOM / component list
- Keycap STL meshes (requires Meshy integration + mesh pipeline)
- Case STL

Spec reference: PRODUCT_SPEC.md section 15.1
"""

from __future__ import annotations

import hashlib
import json
import tempfile
import uuid
import zipfile
from datetime import datetime, timezone
from pathlib import Path

from server.eda.matrix_compiler import apply_matrix_to_layout, compile_matrix
from server.firmware.qmk_generator import write_firmware_files
from server.geometry.plate_generator import PlateConfig, generate_plate_dxf
from server.models.manifest_schema import ArtifactEntry, ExportManifest, ToolchainVersions
from server.models.project import KeyboardProject
from server.validation.engine import validate_project


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def _generate_build_guide(project: KeyboardProject, matrix_rows: int, matrix_cols: int) -> str:
    """Generate a markdown build guide."""
    return f"""# Build Guide — {project.name}

Generated by BreakGen · Revision {project.revision}

## Overview

- **Layout:** {len(project.layout.keys)} keys
- **Switch:** {project.switch_profile.part_id or "Not selected (default MX)"}
- **Matrix:** {matrix_rows} rows × {matrix_cols} columns
- **Controller:** {project.pcb.controller.value.upper()}
- **Diode direction:** {project.pcb.diode_direction.value}

## Files in This Package

| File | Purpose |
|------|---------|
| `plate/plate.dxf` | Switch plate — laser cut from 1.5mm aluminum or acrylic |
| `firmware/info.json` | QMK keyboard definition |
| `firmware/keymap.json` | Default QWERTY keymap |
| `firmware/via.json` | VIA keyboard definition for runtime remapping |
| `validation_report.json` | Validation results for this export |
| `manifest.json` | Artifact hashes and toolchain versions |

## Assembly Steps

1. **Order PCB** — Upload Gerber files to JLCPCB or PCBWay (when PCB generation is available)
2. **Cut plate** — Send `plate.dxf` to a laser cutting service. Material: 1.5mm aluminum or acrylic
3. **Solder components** — Solder diodes (1N4148 SOD-123), controller, and USB-C connector
4. **Install switches** — Press MX switches into the plate, then seat onto the PCB
5. **Flash firmware** — Use QMK Toolbox to flash firmware based on `info.json` and `keymap.json`
6. **Customize keymap** — Load `via.json` in VIA for runtime key remapping

## Notes

- Switch cutout tolerance: 14.0mm ± 0.1mm
- Stabilizer cutouts included for keys ≥ 2u
- Plate kerf compensation: configurable (default 0mm — adjust for your cutter)
"""


def create_export_bundle(
    project: KeyboardProject,
    output_path: str | Path | None = None,
) -> tuple[str, Path]:
    """
    Create a complete export bundle ZIP.

    Returns (bundle_id, zip_path).
    """
    bundle_id = f"bundle_{uuid.uuid4().hex[:12]}"

    with tempfile.TemporaryDirectory() as tmpdir:
        tmp = Path(tmpdir)

        # --- Compile matrix ---
        matrix = compile_matrix(project.layout)
        project.layout = apply_matrix_to_layout(project.layout, matrix)

        # --- Generate plate DXF ---
        plate_dir = tmp / "plate"
        plate_dir.mkdir()
        plate_path = plate_dir / "plate.dxf"
        generate_plate_dxf(project.layout, PlateConfig(), output_path=plate_path)

        # --- Generate firmware metadata ---
        firmware_dir = tmp / "firmware"
        write_firmware_files(project, matrix, firmware_dir)

        # --- Run validation ---
        report = validate_project(project)
        report_path = tmp / "validation_report.json"
        with open(report_path, "w") as f:
            json.dump(report.model_dump(mode="json"), f, indent=2)

        # --- Build guide ---
        guide_path = tmp / "BUILD_GUIDE.md"
        guide_path.write_text(
            _generate_build_guide(project, matrix.matrix_rows, matrix.matrix_cols)
        )

        # --- Manifest ---
        artifacts: list[ArtifactEntry] = []
        for file_path in sorted(tmp.rglob("*")):
            if file_path.is_file() and file_path.name != "manifest.json":
                rel = file_path.relative_to(tmp)
                category = rel.parts[0] if len(rel.parts) > 1 else "doc"
                artifacts.append(ArtifactEntry(
                    path=str(rel),
                    sha256=_sha256(file_path),
                    category=category,
                ))

        manifest = ExportManifest(
            bundle_id=bundle_id,
            project_id=project.project_id,
            revision=project.revision,
            created_at=datetime.now(timezone.utc),
            toolchain=ToolchainVersions(breakgen="0.1.0"),
            artifacts=artifacts,
            validation_report_id=report.report_id,
        )
        manifest_path = tmp / "manifest.json"
        with open(manifest_path, "w") as f:
            json.dump(manifest.model_dump(mode="json"), f, indent=2)

        # --- ZIP everything ---
        if output_path is None:
            output_path = Path(tempfile.mktemp(suffix=".zip"))
        else:
            output_path = Path(output_path)

        with zipfile.ZipFile(output_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for file_path in sorted(tmp.rglob("*")):
                if file_path.is_file():
                    arcname = f"BreakGen_Export/{file_path.relative_to(tmp)}"
                    zf.write(file_path, arcname)

    return bundle_id, output_path
