"""
Export bundle generator.

Creates a ZIP package containing the currently available outputs:
- Mechanical DXF/spec artifacts
- Firmware metadata (QMK info.json, keymap.json, VIA definition)
- Validation report
- Manifest with artifact hashes and toolchain versions
- Build guide (markdown)

Not yet included (requires additional subsystems):
- Gerber files and drill data (requires KiCad backend worker)
- BOM / component list
- Keycap STL meshes (requires Meshy integration + mesh pipeline)
- Case STL

Spec reference: PRODUCT_SPEC.md section 15.1
"""

from __future__ import annotations

import hashlib
import json
import tempfile
import uuid
import zipfile
from datetime import datetime, timezone
from pathlib import Path

from server.config import settings
from server.eda.control_surface_electronics import (
    apply_project_matrix,
    compile_control_surface_electronics,
    compile_project_matrix,
)
from server.firmware.qmk_generator import write_firmware_files
from server.geometry.handheld_shell_generator import generate_handheld_shell_artifacts
from server.geometry.plate_generator import PlateConfig, generate_plate_dxf
from server.models.manifest_schema import ArtifactEntry, ExportManifest, ToolchainVersions
from server.models.project import KeyboardProject, ProductFamily
from server.models.validation_schema import ValidationReport
from server.validation.engine import validate_project


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def _generate_build_guide(
    project: KeyboardProject,
    matrix_rows: int,
    matrix_cols: int,
    *,
    validation_status: str,
    export_readiness: str,
) -> str:
    """Generate a markdown build guide."""
    element_count = len(project.layout.elements) or len(project.layout.keys)
    switch_line = project.switch_profile.part_id or "Not selected / module-specific default"
    electronics = compile_control_surface_electronics(project)
    if project.product_family in {ProductFamily.HANDHELD_COMPANION, ProductFamily.RETRO_HANDHELD}:
        mechanical_rows = """| `shell/front_shell_panel.dxf` | Front shell reference panel with display, button, speaker, and microphone cutouts |
| `shell/back_shell_reference.dxf` | Back shell cavity, battery, and service-access reference |
| `shell/shell_spec.json` | Deterministic handheld shell proof specification |"""
        mechanical_steps = """2. **Prepare shell parts** — Use `shell_spec.json` as the source of truth for enclosure dimensions and `front_shell_panel.dxf` / `back_shell_reference.dxf` as 2D planning references
3. **Fit portable modules** — Check display, battery, USB-C charging/data access, speaker, and microphone placements against the shell spec before committing to CAD or fabrication
4. **Solder and integrate electronics** — Install the controller and control modules according to the exported metadata
5. **Flash proof firmware** — Use `info.json`, `keymap.json`, and `control-map.json` as the current software/hardware contract
6. **Refine enclosure CAD** — Treat this bundle as a deterministic enclosure baseline, not a finished production shell"""
        mechanical_notes = "- This handheld shell path is a proof-grade deterministic baseline, not a full manufacturable enclosure CAD output yet\n- Side-port placement is recorded in `shell_spec.json`; the DXFs are top-down planning references"
    else:
        mechanical_rows = "| `plate/plate.dxf` | Switch plate / control panel — laser cut from 1.5mm aluminum or acrylic |"
        mechanical_steps = """2. **Cut panel / plate** — Send `plate.dxf` to a laser cutting service. Material: 1.5mm aluminum or acrylic
3. **Solder components** — Solder the controller and any control modules indicated by the layout
4. **Install controls** — Mount switches, buttons, encoders, or other surface controls into the panel
5. **Flash firmware** — Use the metadata in `info.json`, `keymap.json`, and `control-map.json` as the baseline for the target firmware path
6. **Refine mappings** — Use the exported layout metadata to continue device-specific mapping and remapping"""
        mechanical_notes = "- Switch cutout tolerance: 14.0mm ± 0.1mm\n- Stabilizer cutouts included for wide switch-like elements where applicable\n- Plate kerf compensation: configurable (default 0mm — adjust for your cutter)"
    return f"""# Build Guide — {project.name}

Generated by BreakGen · Revision {project.revision}

## Overview

- **Layout:** {element_count} placed elements
- **Input baseline:** {switch_line}
- **Matrix:** {matrix_rows} rows × {matrix_cols} columns
- **Controller:** {project.pcb.controller.value.upper()}
- **Diode direction:** {project.pcb.diode_direction.value}
- **Firmware target:** {electronics.firmware_target.replace('_', ' ')}
- **Control protocol:** {electronics.control_protocol.replace('_', ' ')}
- **Validation status:** {validation_status}
- **Export readiness:** {export_readiness.replace('_', ' ')}

## Files in This Package

| File | Purpose |
|------|---------|
{mechanical_rows}
| `firmware/info.json` | Firmware and platform metadata |
| `firmware/keymap.json` | Default control mapping payload |
| `firmware/via.json` | Layout/remapping metadata |
| `firmware/control-map.json` | Family-native control mapping artifact |
| `validation_report.json` | Validation results for this export |
| `manifest.json` | Artifact hashes and toolchain versions |

## Assembly Steps

1. **Order PCB** — Upload Gerber files to JLCPCB or PCBWay (when PCB generation is available)
{mechanical_steps}

## Notes

{mechanical_notes}
- A `candidate` export means the bundle is useful for review and prototyping, but at least one non-blocking validation warning is still open.
"""


def create_export_bundle(
    project: KeyboardProject,
    *,
    validation_report: ValidationReport | None = None,
    export_readiness: str = "prototype_ready",
    output_path: str | Path | None = None,
) -> tuple[str, Path]:
    """
    Create a complete export bundle ZIP.

    Returns (bundle_id, zip_path).
    """
    bundle_id = f"bundle_{uuid.uuid4().hex[:12]}"

    with tempfile.TemporaryDirectory() as tmpdir:
        tmp = Path(tmpdir)

        # --- Compile matrix ---
        matrix, _ = compile_project_matrix(project)
        apply_project_matrix(project, matrix)

        # --- Generate family-specific mechanical artifacts ---
        if project.product_family in {ProductFamily.HANDHELD_COMPANION, ProductFamily.RETRO_HANDHELD}:
            shell_dir = tmp / "shell"
            generate_handheld_shell_artifacts(project.layout, shell_dir)
        else:
            plate_dir = tmp / "plate"
            plate_dir.mkdir()
            plate_path = plate_dir / "plate.dxf"
            generate_plate_dxf(project.layout, PlateConfig(), output_path=plate_path)

        # --- Generate firmware metadata ---
        firmware_dir = tmp / "firmware"
        write_firmware_files(project, matrix, firmware_dir)

        # --- Run validation ---
        report = validation_report or validate_project(project)
        report_path = tmp / "validation_report.json"
        with open(report_path, "w") as f:
            json.dump(report.model_dump(mode="json"), f, indent=2)

        # --- Build guide ---
        guide_path = tmp / "BUILD_GUIDE.md"
        guide_path.write_text(
            _generate_build_guide(
                project,
                matrix.matrix_rows,
                matrix.matrix_cols,
                validation_status=report.status.value,
                export_readiness=export_readiness,
            )
        )

        # --- Manifest ---
        artifacts: list[ArtifactEntry] = []
        for file_path in sorted(tmp.rglob("*")):
            if file_path.is_file() and file_path.name != "manifest.json":
                rel = file_path.relative_to(tmp)
                category = rel.parts[0] if len(rel.parts) > 1 else "doc"
                artifacts.append(ArtifactEntry(
                    path=str(rel),
                    sha256=_sha256(file_path),
                    category=category,
                ))

        manifest = ExportManifest(
            bundle_id=bundle_id,
            project_id=project.project_id,
            revision=project.revision,
            created_at=datetime.now(timezone.utc),
            toolchain=ToolchainVersions(breakgen="0.1.0"),
            artifacts=artifacts,
            validation_report_id=report.report_id,
            validation_status=report.status.value,
            export_readiness=export_readiness,
        )
        manifest_path = tmp / "manifest.json"
        with open(manifest_path, "w") as f:
            json.dump(manifest.model_dump(mode="json"), f, indent=2)

        # --- ZIP everything ---
        if output_path is None:
            export_dir = Path(settings.artifacts_dir) / "projects" / project.project_id / "exports"
            export_dir.mkdir(parents=True, exist_ok=True)
            output_path = export_dir / f"{bundle_id}.zip"
        else:
            output_path = Path(output_path)

        with zipfile.ZipFile(output_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for file_path in sorted(tmp.rglob("*")):
                if file_path.is_file():
                    arcname = f"BreakGen_Export/{file_path.relative_to(tmp)}"
                    zf.write(file_path, arcname)

    return bundle_id, output_path
